[package]
name = "marila-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-s3.workspace = true
aws-credential-types.workspace = true
thiserror.workspace = true
tracing.workspace = true
anyhow.workspace = true
async-trait = "0.1"

[dev-dependencies]
tokio = { workspace = true }
uuid.workspace = true
